use customer_behavior;
select * from customer
limit 5;

-- "Q1. What is the total revenue generated by male vs. female customers?
select Gender, sum(purchase_amount) as Total_Revenue
from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select Customer_Id, Purchase_Amount
from customer
where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount));

-- Q3. Which are the top 5 products with the highest average review rating?
select Item_Purchased, round(avg(review_rating),1) as Avg_Review_Rating
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5; 

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping?
select Shipping_Type, round(avg(purchase_amount),2) as Avg_Purchase_Amount
from customer
where shipping_type = 'Standard' or shipping_type = 'Express'
group by shipping_type
order by Avg_Purchase_Amount desc;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers?
select Subscription_Status, 
	   count(customer_id) as Total_Customers, 
       round(avg(purchase_amount),2) as Avg_Spent, 
       sum(purchase_amount) as Total_Revenue
from customer
group by subscription_status; 

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT Item_Purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS Discount_Rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5; 

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment?

with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS Customer_Segment
FROM customer)

select customer_segment,count(*) AS Total_Customers 
from customer_type 
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT Item_Rank,Category, Item_Purchased, Total_Orders
FROM item_counts
WHERE item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select count(customer_id) as Repeat_Buyers, Subscription_Status
from customer
where previous_purchases >5
group by subscription_status;


-- Q10. What is the revenue contribution of each age group?"
select Age_Group, sum(purchase_amount) as Total_Revenue
from customer
group by age_group
order by total_revenue desc 



